--
-- PostgreSQL database dump
--

\restrict 9S9f5OVzAbYJD9hyQwSEzJLOVec0LaoZvWFZdChMoMQaoD7kRwc9CuBjdbaq1oe

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    picture character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL
);


ALTER TABLE public.categories OWNER TO app_user;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO app_user;

--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO app_user;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_products; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.order_products (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.order_products OWNER TO app_user;

--
-- Name: order_products_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    total numeric(10,2) NOT NULL,
    state character varying(50) NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO app_user;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    price numeric(10,2) NOT NULL,
    stock integer DEFAULT 0 NOT NULL,
    picture character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL,
    category_id bigint
);


ALTER TABLE public.products OWNER TO app_user;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.reviews OWNER TO app_user;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: app_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    address character varying(255) DEFAULT NULL::character varying,
    phone character varying(20) DEFAULT NULL::character varying,
    roles json NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    deleted boolean DEFAULT false NOT NULL
);


ALTER TABLE public.users OWNER TO app_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: app_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.categories (id, name, picture, created_at, deleted_at, deleted) FROM stdin;
1	Semillas	/products/699ead158acf4.png	2026-02-25 08:04:39	\N	f
2	Parafernalia	/products/699eaf10ed51a.webp	2026-02-25 08:13:06	\N	f
3	Cultivo	/products/699eaf1a7405b.png	2026-02-25 08:13:15	\N	f
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260225080414	2026-02-25 08:04:14	970
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: order_products; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.order_products (id, quantity, unit_price, created_at, deleted_at, deleted, order_id, product_id) FROM stdin;
1	1	45.90	2026-02-25 08:04:16	\N	f	1	3
2	1	12.00	2026-02-25 08:04:16	\N	f	1	4
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.orders (id, total, state, created_at, deleted_at, deleted, user_id) FROM stdin;
1	57.90	COMPLETED	2026-02-25 08:04:16	\N	f	2
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.products (id, name, description, price, stock, picture, created_at, deleted_at, deleted, category_id) FROM stdin;
1	Amnesia Haze (3 uds)	Semillas feminizadas de alta calidad con sabor cítrico.	25.50	100	/products/699ead3711397.jpg	2026-02-25 08:04:16	\N	f	1
2	Northern Lights Auto (5 uds)	Variedad autofloreciente clásica, ideal para principiantes.	35.00	50	/products/699eaf4c28371.jpg	2026-02-25 08:04:16	\N	f	1
3	Bong de Vidrio 30cm	Bong de borosilicato resistente con percolador.	45.90	15	/products/699eaf55c10c7.png	2026-02-25 08:04:16	\N	f	2
4	Grinder Metálico 4 partes	Grinder de aluminio con polinizador y espátula.	12.00	200	/products/699eaf5e580dd.jpg	2026-02-25 08:04:16	\N	f	2
5	Kit Fertilizantes Orgánicos	Pack completo para crecimiento y floración.	29.95	30	/products/699eaf64cdb18.png	2026-02-25 08:04:16	\N	f	3
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.reviews (id, rating, comment, created_at, deleted_at, deleted, user_id, product_id) FROM stdin;
1	5	¡Increíble bong! Enfría el humo perfectamente.	2026-02-25 08:04:16	\N	f	2	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: app_user
--

COPY public.users (id, name, email, password, address, phone, roles, created_at, deleted_at, deleted) FROM stdin;
1	Grow Master Admin	admin@example.com	$2y$13$/pRatg5n6EDaFCA1fnRDh.1PBpjRQX.UJ3GA1XyTTn2DSNacfadqq	Calle del Humo 420, Madrid	\N	["ROLE_ADMIN"]	2026-02-25 08:04:15	\N	f
2	Juan Cultivador	user@example.com	$2y$13$FoXbk0Qm8JSVxg37njqFJ.8PmMWjGzE7.PpMftOKeMUi7dE/Q6GV.	Avenida de la Resina 7, Barcelona	\N	["ROLE_USER"]	2026-02-25 08:04:16	\N	f
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.categories_id_seq', 3, true);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: order_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.order_products_id_seq', 2, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.orders_id_seq', 1, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.products_id_seq', 5, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.reviews_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app_user
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: order_products order_products_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT order_products_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_5242b8eb4584665a; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_5242b8eb4584665a ON public.order_products USING btree (product_id);


--
-- Name: idx_5242b8eb8d9f6d38; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_5242b8eb8d9f6d38 ON public.order_products USING btree (order_id);


--
-- Name: idx_6970eb0f4584665a; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_6970eb0f4584665a ON public.reviews USING btree (product_id);


--
-- Name: idx_6970eb0fa76ed395; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_6970eb0fa76ed395 ON public.reviews USING btree (user_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_b3ba5a5a12469de2; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_b3ba5a5a12469de2 ON public.products USING btree (category_id);


--
-- Name: idx_e52ffdeea76ed395; Type: INDEX; Schema: public; Owner: app_user
--

CREATE INDEX idx_e52ffdeea76ed395 ON public.orders USING btree (user_id);


--
-- Name: uniq_identifier_email; Type: INDEX; Schema: public; Owner: app_user
--

CREATE UNIQUE INDEX uniq_identifier_email ON public.users USING btree (email);


--
-- Name: unique_order_product; Type: INDEX; Schema: public; Owner: app_user
--

CREATE UNIQUE INDEX unique_order_product ON public.order_products USING btree (order_id, product_id);


--
-- Name: unique_user_product_review; Type: INDEX; Schema: public; Owner: app_user
--

CREATE UNIQUE INDEX unique_user_product_review ON public.reviews USING btree (user_id, product_id);


--
-- Name: order_products fk_5242b8eb4584665a; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT fk_5242b8eb4584665a FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: order_products fk_5242b8eb8d9f6d38; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT fk_5242b8eb8d9f6d38 FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0f4584665a; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0f4584665a FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: reviews fk_6970eb0fa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_6970eb0fa76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: products fk_b3ba5a5a12469de2; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_b3ba5a5a12469de2 FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;


--
-- Name: orders fk_e52ffdeea76ed395; Type: FK CONSTRAINT; Schema: public; Owner: app_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_e52ffdeea76ed395 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 9S9f5OVzAbYJD9hyQwSEzJLOVec0LaoZvWFZdChMoMQaoD7kRwc9CuBjdbaq1oe

